### ISSUE TITLE
Demande d’autorisation d’intégration à mon projet

### ISSUE THREAD

**Issue by Grahack** [pierrec/js-cuint#2]
Bonjour,
Je vous contacte au sujet de:
https://github.com/pierrec/js-cuint/blob/master/lib/uint64.js
Pourrai-je intégrer à mon prj quelques morceaux de ce
fichier (en faisant référence à ton projet) ?
J’ai juste besoin de *, + et % et pense utiliser ce code aussi sous Rhino.
Mon projet: http://microalg.info.
Grahack

**Comment by pierrec** [comment]
Bonjour,

Réponse très tardive, mais la réponse est bien sûr oui!

Pierre

**Comment by Grahack** [comment]
Merci, j’ai finalement utilisé https://github.com/defunctzombie/int/ qui fournit des entiers arbitrairement grands, ce qui correspondait en fait plus à mon besoin.
