### ISSUE TITLE
the remainder of div result is zero

### ISSUE THREAD

**Issue by bltpanda** [pierrec/js-cuint#3]
In UINT64 class,when div && other > this,why this.remainder = 0?
I think this is an error.
    // other > this: 0
        if ( other.gt(this) ) {
            this.remainder = new UINT64(0)
            this._a00 = 0
            this._a16 = 0
            this._a32 = 0
            this._a48 = 0
            return this
        }

**Comment by pierrec** [comment]
Yes you are right, it should be itself. Fixed in 0.2.1.

Thank you for spotting this!
